In [1]:
%matplotlib tk
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tqdm.notebook import trange
from TaPR_pkg import etapr
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
import time

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import load_model

In [2]:
TRAIN_DATASET = sorted([x for x in Path("D:\\python_project\\hyunmin_project\\ot보안\\data\\HAI 2.0\\training\\").glob("*.csv")])
TRAIN_DATASET

[WindowsPath('D:/python_project/hyunmin_project/ot보안/data/HAI 2.0/training/train1.csv'),
 WindowsPath('D:/python_project/hyunmin_project/ot보안/data/HAI 2.0/training/train2.csv'),
 WindowsPath('D:/python_project/hyunmin_project/ot보안/data/HAI 2.0/training/train3.csv')]

In [3]:
TEST_DATASET = sorted([x for x in Path("D:\\python_project\\hyunmin_project\\ot보안\\data\\HAI 2.0\\testing").glob("*.csv")])
TEST_DATASET

[WindowsPath('D:/python_project/hyunmin_project/ot보안/data/HAI 2.0/testing/test1.csv'),
 WindowsPath('D:/python_project/hyunmin_project/ot보안/data/HAI 2.0/testing/test2.csv'),
 WindowsPath('D:/python_project/hyunmin_project/ot보안/data/HAI 2.0/testing/test3.csv'),
 WindowsPath('D:/python_project/hyunmin_project/ot보안/data/HAI 2.0/testing/test4.csv')]

In [4]:
VALIDATION_DATASET = sorted([x for x in Path("D:\\python_project\\hyunmin_project\\ot보안\\data\\HAI 2.0\\validation").glob("*.csv")])
VALIDATION_DATASET

[WindowsPath('D:/python_project/hyunmin_project/ot보안/data/HAI 2.0/validation/validation.csv')]

In [5]:
def dataframe_from_csv(target):
    return pd.read_csv(target, engine='python').rename(columns=lambda x: x.strip())

def dataframe_from_csvs(targets):
    return pd.concat([dataframe_from_csv(x) for x in targets])

In [6]:
TRAIN_DF_RAW = dataframe_from_csvs(TRAIN_DATASET)
TRAIN_DF_RAW

time        C01  C02  C03       C04     C05      C06  \
0       2020-07-11 00:00:00  395.19528   12   10  52.80456 -1.2648 -1.87531   
1       2020-07-11 00:00:01  395.14420   12   10  52.78931 -1.3147 -1.88294   
2       2020-07-11 00:00:02  395.14420   12   10  52.79694 -1.4032 -1.88294   
3       2020-07-11 00:00:03  395.19528   12   10  52.79694 -1.6074 -1.88294   
4       2020-07-11 00:00:04  395.34866   12   10  52.79694 -1.7811 -1.88294   
...                     ...        ...  ...  ...       ...     ...      ...   
478796  2020-08-10 10:59:56  387.27219   12   10  66.72057 -0.9331 -1.84479   
478797  2020-08-10 10:59:57  387.52774   12   10  66.72057 -0.9996 -1.84479   
478798  2020-08-10 10:59:58  387.47665   12   10  66.72057 -1.2560 -1.84479   
478799  2020-08-10 10:59:59  387.73221   12   10  66.72057 -1.4912 -1.84479   
478800  2020-08-10 11:00:00  387.52774   12   10  66.72057 -1.5727 -1.84479   

              C07       C08      C09  ...        C70  C71      C72       C73  \
0       779.59595  28.02645  10832.0  ...  808.29620  0.0  1.36810   8.79882   
1       780.67328  28.02473  10984.0  ...  819.16809  0.0  1.36810   8.78811   
2       780.06574  28.02817  11120.0  ...  823.51697  0.0  1.36734   8.81787   
3       780.15265  28.02301  11256.0  ...  823.95172  0.0  1.36734   8.87493   
4       781.83160  28.03595  11384.0  ...  827.86560  0.0  1.36810   8.83838   
...           ...       ...      ...  ...        ...  ...      ...       ...   
478796  781.87915  28.02389    880.0  ...  944.84705  0.0  1.32843  15.17817   
478797  787.65070  28.02385    840.0  ...  940.49835  0.0  1.32843  15.17344   
478798  788.50256  28.03085    792.0  ...  935.71472  0.0  1.32919  15.16443   
478799  785.80316  28.02649    752.0  ...  944.84705  0.0  1.32843  15.09001   
478800  780.21381  28.02476    720.0  ...  951.80505  0.0  1.32919  15.08672   

             C74       C75        C76        C77      C78     C79  
0       35.43700  12.01782  305.03113  301.35992  33.6555  6.0951  
1       35.45227  12.01782  304.27161  297.43567  33.6555  5.9262  
2       35.45227  12.01782  303.89179  298.66534  33.6555  5.8101  
3       35.43700  12.01782  303.67474  298.06860  33.6555  5.7509  
4       35.45227  12.01782  303.22266  296.53137  33.6555  5.8547  
...          ...       ...        ...        ...      ...     ...  
478796  35.14710  11.79657  316.89453  296.54950  32.0000  6.6026  
478797  35.13183  11.79657  315.59247  296.15161  32.0000  6.3894  
478798  35.13183  11.79657  313.92865  293.40277  32.0000  6.2584  
478799  35.14710  11.79657  315.61054  302.58972  32.0000  6.4150  
478800  35.14710  11.79657  317.23816  309.00964  32.0000  6.6288  

[921603 rows x 80 columns]

In [7]:
TIMESTAMP_FIELD = "time"
IDSTAMP_FIELD = 'id'
ATTACK_FIELD = "attack"
VALID_COLUMNS_IN_TRAIN_DATASET = TRAIN_DF_RAW.columns.drop([TIMESTAMP_FIELD])
VALID_COLUMNS_IN_TRAIN_DATASET

Index(['C01', 'C02', 'C03', 'C04', 'C05', 'C06', 'C07', 'C08', 'C09', 'C10',
       'C11', 'C12', 'C13', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C20',
       'C21', 'C22', 'C23', 'C24', 'C25', 'C26', 'C27', 'C28', 'C29', 'C30',
       'C31', 'C32', 'C33', 'C34', 'C35', 'C36', 'C37', 'C38', 'C39', 'C40',
       'C41', 'C42', 'C43', 'C44', 'C45', 'C46', 'C47', 'C48', 'C49', 'C50',
       'C51', 'C52', 'C53', 'C54', 'C55', 'C56', 'C57', 'C58', 'C59', 'C60',
       'C61', 'C62', 'C63', 'C64', 'C65', 'C66', 'C67', 'C68', 'C69', 'C70',
       'C71', 'C72', 'C73', 'C74', 'C75', 'C76', 'C77', 'C78', 'C79'],
      dtype='object')

In [8]:
TAG_MIN = TRAIN_DF_RAW[VALID_COLUMNS_IN_TRAIN_DATASET].min()
TAG_MAX = TRAIN_DF_RAW[VALID_COLUMNS_IN_TRAIN_DATASET].max()

In [9]:
def normalize(df):
    ndf = df.copy()
    for c in df.columns:
        if TAG_MIN[c] == TAG_MAX[c]:
            ndf[c] = df[c] - TAG_MIN[c]
        else:
            ndf[c] = (df[c] - TAG_MIN[c]) / (TAG_MAX[c] - TAG_MIN[c])
    return ndf

In [10]:
def boundary_check(df):
    x = np.array(df, dtype=np.float32)
    print(x)
    return np.any(x > 1.0), np.any(x < 0), np.any(np.isnan(x))

In [11]:
def flatten(X):
    flattened_X = np.empty((X.shape[0], X.shape[2]))  # sample x features array.
    for i in range(X.shape[0]):
        flattened_X[i] = X[i, (X.shape[1]-1), :]
    return(flattened_X)

def scale(X, scaler):
    for i in range(X.shape[0]):
        X[i, :, :] = scaler.transform(X[i, :, :])
        
    return X

In [12]:
TRAIN_DF = normalize(TRAIN_DF_RAW[VALID_COLUMNS_IN_TRAIN_DATASET])

In [13]:
train = np.array(TRAIN_DF)
x_train = train.reshape(train.shape[0], 1, train.shape[1])
x_train.shape

(921603, 1, 79)

In [14]:
def conv_auto_model(x):
    n_steps = x.shape[1]
    n_features = x.shape[2]

    keras.backend.clear_session()

    model = keras.Sequential(
        [
            layers.Input(shape=(n_steps, n_features)),
            layers.Conv1D(filters=512, kernel_size=64, padding='same', data_format='channels_last',
                          dilation_rate=1, activation="linear"),
            layers.Dense(128),
            layers.LSTM(
                units=64, activation="relu", name="lstm_1", return_sequences=False
            ),
            layers.Dense(64),
            layers.RepeatVector(n_steps),
            layers.LSTM(
                units=64, activation="relu", name="lstm_2", return_sequences=True
            ),
            layers.Dense(64),
            layers.Conv1D(filters=512, kernel_size=64, padding='same', data_format='channels_last',
                          dilation_rate=1, activation="linear"),
            layers.Dense(128),
            layers.TimeDistributed(layers.Dense(x.shape[2], activation='linear'))
        ]
    )
    return model

In [15]:
# model = conv_auto_model(x_train)
# model.compile(optimizer='adam', loss='mse')
# model.summary()

# early_stopping = EarlyStopping(monitor='val_loss', patience=5)

# epochs = 5
# batch = 64

# # fit
# history = model.fit(x_train, x_train,
#                      epochs=epochs, batch_size=batch,
#                      validation_split=0.2, callbacks=[early_stopping]).history

# model.save('conv_auto_li_relu_dense(128,64)_early_512_64_64_0.2_%s_%s.h5' % (epochs, batch))

In [16]:
model = load_model('conv_auto_li_relu_dense(128,64)_early_512_64_64_0.2_50_64.h5')

In [17]:
VALIDATION_DF_RAW = dataframe_from_csvs(VALIDATION_DATASET)
VALIDATION_DF_RAW.to_csv('VALIDATION_DF_RAW.csv')
VALIDATION_DF_RAW

time        C01   C02  C03       C04     C05      C06  \
0      2020-07-07 15:00:00  402.70947  12.0   10  51.95007 -1.0189 -1.86768   
1      2020-07-07 15:00:01  402.81174  12.0   10  51.96533 -1.2637 -1.86768   
2      2020-07-07 15:00:02  402.76062  12.0   10  51.96533 -1.5398 -1.86768   
3      2020-07-07 15:00:03  402.81174  12.0   10  51.98822 -1.6212 -1.86768   
4      2020-07-07 15:00:04  402.91394  12.0   10  51.90429 -1.5631 -1.86768   
...                    ...        ...   ...  ...       ...     ...      ...   
43196  2020-07-08 02:59:56  397.08661  12.0   10  66.58325 -1.2052 -1.83716   
43197  2020-07-08 02:59:57  397.18887  12.0   10  66.58325 -0.9256 -1.83716   
43198  2020-07-08 02:59:58  397.13776  12.0   10  66.58325 -0.7843 -1.83716   
43199  2020-07-08 02:59:59  397.34222  12.0   10  66.58325 -0.7646 -1.83716   
43200  2020-07-08 03:00:00  397.49557  12.0   10  66.58325 -0.9083 -1.83716   

             C07       C08  C09  ...  C71      C72       C73       C74  \
0      789.76508  28.03162  688  ...  0.0  1.34293  10.89290  34.88770   
1      789.13147  28.02301  648  ...  0.0  1.34216  10.80512  34.88770   
2      785.81653  28.02993  616  ...  0.0  1.34369  10.80029  34.88770   
3      785.42438  28.02993  584  ...  0.0  1.34445  10.80579  34.88770   
4      782.99249  28.02990  552  ...  0.0  1.34293  10.81415  34.90295   
...          ...       ...  ...  ...  ...      ...       ...       ...   
43196  786.93738  28.03250    0  ...  0.0  1.35971  16.19496  35.22338   
43197  783.44989  28.02304    0  ...  0.0  1.35971  16.23927  35.23864   
43198  784.86780  28.02814    0  ...  0.0  1.35818  16.20675  35.23864   
43199  785.51416  28.02294    0  ...  0.0  1.35818  16.17168  35.25391   
43200  786.98297  28.02990    0  ...  0.0  1.35895  16.10412  35.22338   

            C75        C76        C77       C78     C79  attack  
0      12.26196  380.31683  386.26666  32.59527  5.6330       0  
1      12.26196  380.02747  386.30286  32.59527  5.4158       0  
2      12.26196  381.52850  389.73883  32.59527  5.5532       0  
3      12.26196  382.08911  388.94311  32.59527  5.7833       0  
4      12.26196  383.44543  389.72082  32.59527  6.0309       0  
...         ...        ...        ...       ...     ...     ...  
43196  12.01019  390.13672  394.91107  31.81634  5.2977       0  
43197  12.01019  390.24518  397.35248  31.81634  5.3188       0  
43198  12.01019  390.46222  396.70142  31.81634  5.1800       0  
43199  12.01019  391.78241  397.73218  31.81634  4.8763       0  
43200  12.01019  391.31219  397.24390  31.81634  4.5790       0  

[43201 rows x 81 columns]

In [46]:
VALIDATION_DF = normalize(VALIDATION_DF_RAW[VALID_COLUMNS_IN_TRAIN_DATASET])

In [19]:
#VALIDATION_DF.plot()

In [72]:
# valid 그래프를 보고 앞부분 정상인데 값이 튀는 변수가 있어서 조절
VALIDATION_DF['C75'][:2110] = 0.95

In [73]:
val = np.array(VALIDATION_DF)
x_val = val.reshape(val.shape[0], 1, val.shape[1])
x_val.shape

(43201, 1, 79)

In [74]:
boundary_check(VALIDATION_DF)

[[0.45158097 0.         0.         ... 0.5797802  0.52712005 0.4013713 ]
 [0.45256948 0.         0.         ... 0.5799144  0.52712005 0.32340166]
 [0.45207536 0.         0.         ... 0.5926521  0.52712005 0.37272498]
 ...
 [0.39772758 0.         0.         ... 0.6184636  0.17970447 0.23875508]
 [0.3997038  0.         0.         ... 0.62228477 0.17970447 0.129734  ]
 [0.401186   0.         0.         ... 0.62047464 0.17970447 0.02301037]]


(True, True, False)

In [75]:
start = time.time()
valid_x_predictions = model.predict(x_val)
print(valid_x_predictions.shape)

error = flatten(x_val) - flatten(valid_x_predictions)
print((flatten(x_val) - flatten(valid_x_predictions)).shape)

valid_mse = np.mean(np.power(flatten(x_val) - flatten(valid_x_predictions), 2), axis=1)
print(valid_mse.shape)
print(time.time()-start)

(43201, 1, 79)
(43201, 79)
(43201,)
7.202211141586304


In [76]:
error_df = pd.DataFrame({'Reconstruction_error': valid_mse, 
                         'True_class':list(VALIDATION_DF_RAW['attack'])})
precision_rt, recall_rt, threshold_rt = metrics.precision_recall_curve(error_df['True_class'], error_df['Reconstruction_error'])

plt.figure(figsize=(8,5))
plt.plot(threshold_rt, precision_rt[1:], label='Precision')
plt.plot(threshold_rt, recall_rt[1:], label='Recall')
plt.xlabel('Threshold'); plt.ylabel('Precision/Recall')
plt.legend()
#plt.show()

In [77]:
index_cnt = [cnt for cnt, (p, r) in enumerate(zip(precision_rt, recall_rt)) if p==r][0]
print('precision: ',precision_rt[index_cnt],', recall: ',recall_rt[index_cnt])

# fixed Threshold
threshold_fixed = threshold_rt[index_cnt]
print('threshold: ',threshold_fixed)

precision:  0.9411764705882353 , recall:  0.9411764705882353
threshold:  0.00036586847637974846


In [78]:
#이동평균
mean_window = error_df['Reconstruction_error'].rolling(50).mean()
window_error = mean_window.fillna(0)
window_error

0        0.000000
1        0.000000
2        0.000000
3        0.000000
4        0.000000
           ...   
43196    0.000138
43197    0.000138
43198    0.000137
43199    0.000135
43200    0.000133
Name: Reconstruction_error, Length: 43201, dtype: float64

In [79]:
valid_error_df = pd.DataFrame({'Reconstruction_error': window_error ,
                         'True_class': list(VALIDATION_DF_RAW['attack'])})
groups = error_df.groupby('True_class')
fig, ax = plt.subplots(figsize=(20,20))

for name, group in groups:
    ax.plot(group.index, group.Reconstruction_error, marker='o', ms=3.5, linestyle='',
            label= "Break" if name == 1 else "Normal")
    
ax.hlines(0.00036, ax.get_xlim()[0], ax.get_xlim()[1], colors="r", zorder=100, label='Threshold')
#ax.hlines(0.001, ax.get_xlim()[0], ax.get_xlim()[1], colors="r", zorder=100, label='Threshold')
#ax.hlines(3, ax.get_xlim()[0], ax.get_xlim()[1], colors="r", zorder=100, label='Threshold')
ax.legend()

plt.title("Reconstruction error for different classes")
plt.ylabel("Reconstruction error")
plt.xlabel("Data point index")

Text(0.5, 0, 'Data point index')

In [80]:
pred_y = [1 if e > 0.0004 else 0 for e in valid_error_df['Reconstruction_error'].values]
pred_y = np.array(pred_y)
pred_y.shape

(43201,)

In [81]:
ATTACK_LABELS = np.array(VALIDATION_DF_RAW[ATTACK_FIELD])
FINAL_LABELS = np.array(pred_y)

ATTACK_LABELS.shape[0] == FINAL_LABELS.shape[0]

True

In [82]:
TaPR = etapr.evaluate(anomalies=ATTACK_LABELS, predictions=FINAL_LABELS)
print(f"F1: {TaPR['f1']:.3f} (TaP: {TaPR['TaP']:.3f}, TaR: {TaPR['TaR']:.3f})")
print(f"# of detected anomalies: {len(TaPR['Detected_Anomalies'])}")
print(f"Detected anomalies: {TaPR['Detected_Anomalies']}")

F1: 0.996 (TaP: 0.998, TaR: 0.994)
# of detected anomalies: 5
Detected anomalies: ['1', '2', '3', '4', '5']


In [31]:
TEST_DF_RAW = dataframe_from_csvs(TEST_DATASET)
TEST_DF_RAW

time        C01   C02  C03       C04     C05       C06  \
0      2020-07-09 15:00:00  384.30737  12.0   10  70.35980 -1.6171  -1.79901   
1      2020-07-09 15:00:01  384.30737  12.0   10  70.35980 -1.7606  -1.79901   
2      2020-07-09 15:00:02  384.20517  12.0   10  70.35980 -1.7606  -1.80664   
3      2020-07-09 15:00:03  384.25626  12.0   10  70.35980 -1.7814  -1.79901   
4      2020-07-09 15:00:04  384.20517  12.0   10  70.35980 -1.7370  -1.79901   
...                    ...        ...   ...  ...       ...     ...       ...   
92396  2020-07-31 12:29:56  420.08923  12.0   10  48.31848 -0.8706  97.19238   
92397  2020-07-31 12:29:57  420.08923  12.0   10  48.31848 -0.7498  97.19238   
92398  2020-07-31 12:29:58  420.24258  12.0   10  48.31848 -0.6076  97.19238   
92399  2020-07-31 12:29:59  420.24258  12.0   10  48.31848 -0.4618  97.19238   
92400  2020-07-31 12:30:00  420.29373  12.0   10  48.31848 -0.3661  97.20001   

             C07       C08  C09  ...        C70    C71      C72       C73  \
0      774.20752  28.02385  136  ...  936.58447    0.0  1.35437  13.97231   
1      772.58758  28.02730  136  ...  940.93317    0.0  1.35437  13.93358   
2      772.58758  28.02730  136  ...  936.58447    0.0  1.35513  13.95248   
3      777.48810  28.02905  136  ...  933.54034    0.0  1.35513  13.89971   
4      778.42212  28.03169  136  ...  944.41223    0.0  1.35437  13.94603   
...          ...       ...  ...  ...        ...    ...      ...       ...   
92396  786.54382  28.03253  232  ...  824.82147  100.0  1.35666   9.62203   
92397  784.07184  28.03598  224  ...  823.51697  100.0  1.35513   9.48747   
92398  786.83881  28.02642  208  ...  824.82147  100.0  1.35666   9.57787   
92399  786.66138  28.03341  200  ...  833.51904  100.0  1.35513   9.56291   
92400  785.72290  28.03247  192  ...  827.43085  100.0  1.35590   9.53689   

            C74       C75        C76        C77   C78     C79  
0      35.22338  12.02545  293.51129  283.92651  32.0  6.5059  
1      35.20813  12.02545  292.67938  283.36591  32.0  6.3079  
2      35.20813  12.02545  291.90179  282.93189  32.0  6.3079  
3      35.20813  12.02545  291.59430  282.06378  32.0  6.1203  
4      35.20813  12.02545  289.87628  283.67334  32.0  5.9543  
...         ...       ...        ...        ...   ...     ...  
92396  36.47460  11.78894  357.27722  361.14728  32.0  6.2809  
92397  36.47460  11.78894  357.29529  359.84521  32.0  6.3602  
92398  36.48986  11.78894  357.27722  360.60474  32.0  6.3742  
92399  36.48986  11.78894  357.80170  357.42188  32.0  6.2864  
92400  36.47460  11.78894  357.07825  358.65161  32.0  6.0371  

[358804 rows x 80 columns]

In [32]:
TEST_DF = normalize(TEST_DF_RAW[VALID_COLUMNS_IN_TRAIN_DATASET]).ewm(alpha=0.9).mean()
TEST_DF

C01  C02  C03       C04       C05       C06       C07       C08  \
0      0.273715  0.0  0.0  0.828325  0.225882  0.000999  0.318761  0.333825   
1      0.273715  0.0  0.0  0.828325  0.171634  0.000999  0.300187  0.426398   
2      0.272825  0.0  0.0  0.828325  0.166747  0.000930  0.298514  0.434738   
3      0.273182  0.0  0.0  0.828325  0.158478  0.000992  0.353980  0.482056   
4      0.272773  0.0  0.0  0.828325  0.174269  0.000998  0.370123  0.556914   
...         ...  ...  ...       ...       ...       ...       ...       ...   
92396  0.619520  0.0  0.0  0.073426  0.532147  0.998079  0.476720  0.581066   
92397  0.619561  0.0  0.0  0.073426  0.581096  0.998079  0.446527  0.680775   
92398  0.620899  0.0  0.0  0.073426  0.639210  0.998079  0.474916  0.436791   
92399  0.621033  0.0  0.0  0.073426  0.699587  0.998079  0.475741  0.598077   
92400  0.621491  0.0  0.0  0.073426  0.741441  0.998148  0.465171  0.589235   

            C09       C10  ...       C70  C71       C72       C73       C74  \
0      0.010417  0.139867  ...  0.677723  0.0  0.317842  0.452044  0.236483   
1      0.010417  0.137445  ...  0.680584  0.0  0.317842  0.450701  0.230344   
2      0.010417  0.137227  ...  0.678007  0.0  0.318290  0.451229  0.229791   
3      0.010417  0.190063  ...  0.675769  0.0  0.318335  0.449470  0.229736   
4      0.010417  0.266280  ...  0.682626  0.0  0.317891  0.450884  0.229731   
...         ...       ...  ...       ...  ...       ...       ...       ...   
92396  0.017489  0.358745  ...  0.596406  1.0  0.319337  0.285888  0.790598   
92397  0.016853  0.386044  ...  0.595956  1.0  0.318439  0.281450  0.790543   
92398  0.015748  0.453718  ...  0.596761  1.0  0.319252  0.284110  0.796619   
92399  0.015116  0.563381  ...  0.602505  1.0  0.318431  0.283862  0.797227   
92400  0.014532  0.705708  ...  0.599115  1.0  0.318803  0.282944  0.791206   

            C75       C76       C77      C78       C79  
0      0.944440  0.225971  0.200389  0.26162  0.714722  
1      0.944440  0.223121  0.198499  0.26162  0.650106  
2      0.944440  0.220223  0.196880  0.26162  0.644285  
3      0.944440  0.218893  0.193823  0.26162  0.583093  
4      0.944440  0.212932  0.198888  0.26162  0.523348  
...         ...       ...       ...      ...       ...  
92396  0.083339  0.466152  0.485809  0.26162  0.622130  
92397  0.083339  0.466370  0.482229  0.26162  0.658390  
92398  0.083339  0.466330  0.484406  0.26162  0.666539  
92399  0.083339  0.468106  0.474004  0.26162  0.638988  
92400  0.083339  0.465829  0.477066  0.26162  0.555689  

[358804 rows x 79 columns]

In [33]:
boundary_check(TEST_DF)

[[0.27371535 0.         0.         ... 0.20038876 0.26161984 0.7147216 ]
 [0.27371535 0.         0.         ... 0.19849946 0.26161984 0.6501059 ]
 [0.27282545 0.         0.         ... 0.19687971 0.26161984 0.64428467]
 ...
 [0.6208987  0.         0.         ... 0.48440555 0.26161984 0.666539  ]
 [0.62103254 0.         0.         ... 0.4740037  0.26161984 0.6389876 ]
 [0.62149084 0.         0.         ... 0.47706646 0.26161984 0.555689  ]]


(True, True, False)

In [34]:
test = np.array(TEST_DF)
x_test = test.reshape(test.shape[0], 1, test.shape[1])
x_test.shape

(358804, 1, 79)

In [35]:
start = time.time()
test_x_predictions = model.predict(x_test)
#print(test_x_predictions)
print(test_x_predictions.shape)
#print((flatten(x_test) - flatten(test_x_predictions)).shape)
test_mse = np.mean(np.power(flatten(x_test) - flatten(test_x_predictions), 2), axis=1)
print(test_mse.shape)
print(time.time()-start)

(358804, 1, 79)
(358804,)
57.64484715461731


In [36]:
test_error = pd.DataFrame({'Reconstruction_error': test_mse})

In [37]:
test_move = test_error['Reconstruction_error'].rolling(71).mean()

test_d = test_move.fillna(0)
test_d

0         0.000000
1         0.000000
2         0.000000
3         0.000000
4         0.000000
            ...   
358799    0.000335
358800    0.000333
358801    0.000332
358802    0.000330
358803    0.000328
Name: Reconstruction_error, Length: 358804, dtype: float64

In [38]:
movemean_test = pd.DataFrame({'Reconstruction_error': test_d})

In [39]:
pred_y_test = [1 if e > 0.000426 else 0 for e in movemean_test['Reconstruction_error'].values]
pred_y_test = np.array(pred_y_test)
pred_y_test.shape

(358804,)

In [40]:
submission = pd.read_csv('D:\\python_project\\hyunmin_project\\ot보안\\data\\HAI 2.0\\sample_submission.csv')
submission.index = submission['time']
submission['attack'] = pred_y_test

In [41]:
submission['attack'].value_counts()

0    349651
1      9153
Name: attack, dtype: int64

In [42]:
test_error_df = pd.DataFrame({'Reconstruction_error': test_d,
                         'True_class': list(submission['attack'])})
groups = test_error_df.groupby('True_class')
fig, ax = plt.subplots(figsize=(20,20))

for name, group in groups:
    ax.plot(group.index, group.Reconstruction_error, marker='o', ms=3.5, linestyle='',
            label= "Break" if name == 1 else "Normal")
    
ax.hlines(0.002, ax.get_xlim()[0], ax.get_xlim()[1], colors="r", zorder=100, label='Threshold')
#ax.hlines(0.001, ax.get_xlim()[0], ax.get_xlim()[1], colors="r", zorder=100, label='Threshold')
#ax.hlines(3, ax.get_xlim()[0], ax.get_xlim()[1], colors="r", zorder=100, label='Threshold')
ax.legend()

plt.title("Reconstruction error for different classes")
plt.ylabel("Reconstruction error")
plt.xlabel("Data point index")

Text(0.5, 0, 'Data point index')

In [43]:
submission.to_csv('predic_71_426.csv', index=False)